nav:
  - text: Home
    link: /

sidebar:
  "/":
    - text: 總表
      items:
        - text: 回到首頁
          link: /
        - text: OSINT
          link: /osint/
        - text: 第二題
          link: /topic2.html
        - text: 第三題
          link: /topic3.html